CommitMsg:
  CapitalizedSubject:
    enabled: true
  HardTabs:
    enabled: true
  RussianNovel:
    enabled: true
  SingleLineSubject:
    enabled: true
  TextWidth:
    enabled: true
  TrailingPeriod:
    enabled: true
PreCommit:
  AuthorEmail:
    enabled: true
  AuthorName:
    enabled: true
  Brakeman: # Performs static code security checking.
    enabled: false
  BrokenSymlinks:
    enabled: true
  BundleCheck:
    enabled: true
  CssLint:
    enabled: true
  HamlLint:
    enabled: true
  HardTabs:
    enabled: true
  HtmlTidy: # Uses the `tidy` executable (installed on OS X by default).
    enabled: true
  ImageOptim:
    enabled: true
  Jscs: # Checks for JavaScript style.
    enabled: true
  JsHint: # Checks for JavaScript best practices.
    enabled: true
  JsonSyntax:
    enabled: true
  LocalPathsInGemfile:
    enabled: true
  MergeConflicts:
    enabled: true
  PryBinding:
    enabled: true
  Reek:
    enabled: false
  RuboCop:
    enabled: true
    problem_on_unmodified_line: warn
  ScssLint:
    enabled: true
  TrailingWhitespace:
    enabled: true
  TravisLint: # Checks Travis CI configurations. We use Travis for our open-
              # source repositories.
    enabled: true
  YamlSyntax:
    enabled: true
