rvm:
- 2.6
- 2.5
- 2.4 # Keep this in sync with .rubocop.yml
# We test up to the latest version of Ruby here, and test these Ruby versions
# against all support ActiveRecord versions. One test will be "duplicated"
# below when we calculate code coverage, but I don't know how to avoid that and
# still test all combinations of Ruby and ActiveRecord.
script:
- bundle exec rspec
env:
  matrix:
  - ACTIVERECORD_VERSION="~> 5.2.0"
  - ACTIVERECORD_VERSION="~> 5.1.0"
  - ACTIVERECORD_VERSION="~> 5.0.0"
matrix:
  include:
  - rvm: 2.6
    script:
    - bundle exec rspec
    - gem install --no-document rubocop rubocop-rspec-focused && rubocop
    env:
    - CODE_COVERAGE=true
    - ACTIVERECORD_VERSION="~> 5.2.0"
branches:
  only:
  - master
  # We always run tests for PRs. This prevents running PR tests twice (once "for
  # the PR" and once "for the branch"), though we do want tests to run always
  # run on master.
notifications:
  email: false
  slack:
    secure: entGnl4bTxXdRohlblOyXESCMpvCRNI4no7hb35EO8NRNtnfAYBaaAaKQECZdTPy/4eg9hxg9v3jGSQNXZz6PBm+Zp/ZI3PEicmHeoALbtLafOnXPugqM0lV/XZ7TYlFNn4h/SDKZDWeFBV70hkdQBjlUL09nN0Nk/VIsc0x8daPoA1ZAa3oFGdssSXObO9C52cqcDBJ16JzBjf0PUjWkTE0iR+fhuqp1o8NcQgY8kQvxuR5HXHdmL5kHPe2RRJF1aY2QWdoaosAl5yqGkJ2p+RS/5y3DQ5Bo51uFuRKvQ5tvVxvHOO7kEvNpaCMAr6r/Tov6aOIvBAegOxhX1/xOIsMEbiPf9/YT6SPSIUXyy7pOK0p+OqviXKz9tdTLPjIPqjZvPzYeXEkg0HiPdshqs02uGpo+LXm0Zbgr44NF0qgUrPbPrkcDR7m7/cHW5P59M8fAID9FJLQkolXGcoyiIdg4T08y01mcINRZUtVejykiCPGH8q4+9g6ymIFt0P0yJJWl9dAQzqdzOJypdL5VnHgeZUbf/3MkxLcRC3o9n9/YbGJlx7IsBWlMMrY2MmTiRSp1/byde3/N47mhWnb/L6teoOA/8EM3AVcedBTAtuzxBmeeK5Acp6sDUMyNOZKj/72CwvVPFmXOuZ1+IF2r0qLY3oBIyThtADTlY/lplc=
